function moves(type,place,id,menu,value) {
	var form = document.createElement("FORM");
	form.method = "POST";
	form.style.display = "none";
	document.body.appendChild(form);
	form.action = "/admin/edit_menu";
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "type";
	input.value = type;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "place";
	input.value = place;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "id";
	input.value = id;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "menu";
	input.value = menu;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "href";
	input.value = value;
	form.appendChild(input);
	form.submit();
}

function movesClock(type,place,id,color,style) {
	var form = document.createElement("FORM");
	form.method = "POST";
	form.style.display = "none";
	document.body.appendChild(form);
	form.action = "/admin/edit_menu";
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "type";
	input.value = type;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "place";
	input.value = place;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "id";
	input.value = id;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "color";
	input.value = color;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "style";
	input.value = style;
	form.appendChild(input);
	form.submit();
}

function movesUsers(type,place,id,option,link) {
	var form = document.createElement("FORM");
	form.method = "POST";
	form.style.display = "none";
	document.body.appendChild(form);
	form.action = "/admin/edit_menu";
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "type";
	input.value = type;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "place";
	input.value = place;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "id";
	input.value = id;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "option";
	input.value = option;
	form.appendChild(input);
	input = document.createElement("INPUT");
	input.type = "hidden";
	input.name = "link";
	input.value = link;
	form.appendChild(input);
	form.submit();
}